name: Deploy to Beget (rsync)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v3

    - name: Настройка SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Деплой через rsync
      run: |
        # Создаем временную директорию с файлами для деплоя
        mkdir -p deploy_temp
        cp -r index.html app.js style.css manifest.json sw.js vercel.json package.json deploy_temp/
        
        # Деплоим через rsync
        rsync -avz --delete \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='.github' \
          --exclude='Temp' \
          --exclude='Crowdfunding' \
          --exclude='*.md' \
          --exclude='*.txt' \
          --exclude='*.log' \
          deploy_temp/ chuchuc3@chuchuc3.beget.tech:../shiftlog/public_html/
        
        # Очищаем временную директорию
        rm -rf deploy_temp

    - name: Проверка деплоя
      run: |
        echo "Проверяем доступность сайта..."
        sleep 5
        curl -f https://chuchuc3.beget.tech || echo "Сайт еще не доступен" 